services:
  postgres:
    image: postgres
    container_name: postgres_containerx
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresqlx/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_containerx
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
