server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-api
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: 2e7d9c15a3b24716b8f1c3a7e56d8914a45b67fcd2e4f89a736df1c2b8a3f4c1
  expiration:
    access: 3600000 # 1 hora en milisegundos
    refresh: 604800000 # 7 días en milisegundos

